### ISSUE TITLE
Variables

### ISSUE THREAD

**Issue by markusmoenig** [nerdsupremacist/Ogma#7]
Hi, this looks cool. Is it still supported ?

I am looking into writing an easy meta language which would transpile to Metal. But for this I would need Variables, any plans to adding these in the future ?

Thanks

**Comment by nerdsupremacist** [comment]
Hi Markus,

I'm not sure I understand what it is you want. But we can definitely check if there's some cool feature we can look at here.

So do you mean having like variables to parametrize parsing? Or do you mean variables in the language you want to parse? 

If it's the latter I'm not sure there's much we can do at this level. This library should give you the equivalent to a Syntax Tree. You have to specify how variables look and then deal with them afterwards.
Here's an example of a repo that is parsing variables: https://github.com/nerdsupremacist/graphql-syntax

**Comment by markusmoenig** [comment]
Thanks for the answer, yes that was what I was looking for, the link helps a lot.
